#BROWSER NAME
browserName=chrome


#APPLICATION URL
appURL=https://www.naukri.com/


#LOGIN CREDENTIALS
emailID=manoprasadark@gmail.com
password=@Mano#D045


#SCREENSHOT PATH
screenshotPath=.//Screenshot

#EXCEL URL
excelPath=C:/Users/Mano/IdeaProjects/Naukri_Project/src/test/resources/Excel.xlsx


#PERSONAL CREDENTIALS
profileName=ManoPrasad R

profileSummary = Results-driven Software Test Engineer with 3+ years of experience in Manual and Automation Testing. Experienced in designing, developing, and maintaining automation frameworks using Java, Selenium WebDriver, TestNG, Maven, Page Object Model (POM), and Data-Driven Framework (DDF). Skilled in functional, regression, smoke, sanity, and cross-browser testing. Hands-on experience with Cucumber (BDD), SQL, Git, GitHub, Jenkins, JIRA, and Agile Scrum methodologies. Strong knowledge of SDLC, STLC, defect life cycle, and test case design. Passionate about delivering high-quality software through efficient automation and continuous improvement.

#REPORT
start=C:/Users/Mano/IdeaProjects/Naukri_Project/Reports
end=C:/Users/Mano/IdeaProjects/Naukri_Project/Reports/index.html





mobileNumber=6383063090
workstatus=I'm a Fresher
currentCity=Chennai
country=India

highestQualification=Graduation
course=B.E.
courseType=FullTime
specialization=Mechanical Engineering
university= Indian Instiute of Technology,Chennai
startingYear=2018
passingYear=2022




